2022-09-19 15:06:40 INFO: WORK_DIR: /mnt/300G/data/2022-09-19-150639
2022-09-19 15:06:40 INFO: LOG: /mnt/300G/data/2022-09-19-150639/cygnus-weekly.log
~/projects/ldms-test ~/projects/ldms-test
/mnt/300G/data/2022-09-19-150639 ~/projects/ldms-test ~/projects/ldms-test
2022-09-19 15:06:40 INFO: Does not have RDMA, skip building on host
d0f0efc0919dafdb8387c7a7dc69027d5e8949d5
2022-09-19 15:06:40 INFO: Skip building containerized binary because GIT SHA has not changed: c7577d494f5924b98137084e73d2e95f2e804958
2022-09-19 15:06:40 INFO: -- Installation process succeeded --
2022-09-19 15:06:40 INFO: ---------------------------------------------------------------
~/projects/ldms-test /mnt/300G/data/2022-09-19-150639
~/projects/ldms-test/weekly-report ~/projects/ldms-test /mnt/300G/data/2022-09-19-150639
HEAD is now at 397bffa 2022-09-19-141645
[master a8fbc69] 2022-09-19-150639
 2 files changed, 14 insertions(+), 298 deletions(-)
 rewrite test-all.log (98%)
To github.com:narategithub/weekly-report
   397bffa..a8fbc69  master -> master
~/projects/ldms-test /mnt/300G/data/2022-09-19-150639
2022-09-19 15:06:42 INFO: ==== OVIS+SOS Installation Completed ====
2022-09-19 15:06:42 INFO: ==== Start batch testing ====
~/projects/ldms-test /mnt/300G/data/2022-09-19-150639 ~/projects/ldms-test ~/projects/ldms-test
2022-09-19 15:06:42 INFO: ======== agg_slurm_test ========
2022-09-19 15:06:42 INFO: CMD: python3 agg_slurm_test --prefix /home/narate/projects/ldms-test/ldms-containers/ovis --runtime docker --image ovishpc/ldms-dev --src /mnt/300G/data --data_root /mnt/300G/data/2022-09-19-150639/data/agg_slurm_test
2022-09-19 15:06:42,780 TADA INFO starting test `agg_slurm_test`
2022-09-19 15:06:42,780 TADA INFO   test-id: c75ca24864cf74b394f9a4be14913d4070c3986a9063ae8fe6cbf160596b789f
2022-09-19 15:06:42,780 TADA INFO   test-suite: LDMSD
2022-09-19 15:06:42,780 TADA INFO   test-name: agg_slurm_test
2022-09-19 15:06:42,780 TADA INFO   test-user: narate
2022-09-19 15:06:42,780 TADA INFO   commit-id: d0f0efc0919dafdb8387c7a7dc69027d5e8949d5
2022-09-19 15:06:42,781 __main__ INFO -- Get or create the cluster --
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/networks/narate-agg_slurm_test-d0f0efc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 664, in _get
    net = dc.networks.get(name)
  File "/usr/lib/python3/dist-packages/docker/models/networks.py", line 180, in get
    self.client.api.inspect_network(network_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/network.py", line 213, in inspect_network
    return self._result(res, json=True)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("network narate-agg_slurm_test-d0f0efc not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/narate/projects/ldms-test/LDMS_Test.py", line 1615, in get
    cluster = _cls._get(name)
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 667, in _get
    raise LookupError()
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f15a28a6250>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='whiteknight', port=2375): Max retries exceeded with url: /v1.35/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15a28a6250>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "agg_slurm_test", line 396, in <module>
    cluster = LDMSDCluster.get(spec["name"], create = True, spec = spec)
  File "/home/narate/projects/ldms-test/LDMS_Test.py", line 1622, in get
    return _cls.create(spec)
  File "/home/narate/projects/ldms-test/LDMS_Test.py", line 1593, in create
    cluster = _cls._create(spec)
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 416, in _create
    return cls.__create(**kwargs)
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 498, in __create
    tbl = [ [ cl.info()["ContainersRunning"], 0, cl ] for cl in clients ]
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 498, in <listcomp>
    tbl = [ [ cl.info()["ContainersRunning"], 0, cl ] for cl in clients ]
  File "/usr/lib/python3/dist-packages/docker/client.py", line 179, in info
    return self.api.info(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 95, in info
    return self._result(self._get(self._url("/info")), True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='whiteknight', port=2375): Max retries exceeded with url: /v1.35/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f15a28a6250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-09-19 15:06:42,824 TADA INFO assertion 1, ldms_ls agg-2: skipped
2022-09-19 15:06:42,824 TADA INFO assertion 2, slurm data verification: skipped
2022-09-19 15:06:42,824 TADA INFO assertion 3, meminfo data verification: skipped
2022-09-19 15:06:42,824 TADA INFO assertion 4, (SYS/JOB) PAPI data verification: skipped
2022-09-19 15:06:42,824 TADA INFO test agg_slurm_test ended
2022-09-19 15:06:52 INFO: ----------------------------------------------
2022-09-19 15:06:53 INFO: ======== maestro_cfg_test ========
2022-09-19 15:06:53 INFO: CMD: python3 maestro_cfg_test --prefix /home/narate/projects/ldms-test/ldms-containers/ovis --runtime docker --image ovishpc/ldms-dev --src /mnt/300G/data --data_root /mnt/300G/data/2022-09-19-150639/data/maestro_cfg_test
2022-09-19 15:06:53,383 TADA INFO starting test `maestro_cfg_test`
2022-09-19 15:06:53,383 TADA INFO   test-id: 78cfa183918e37ffbcfaf449565386ea8a5a10e0af92d643a6a546119a19d284
2022-09-19 15:06:53,383 TADA INFO   test-suite: LDMSD
2022-09-19 15:06:53,383 TADA INFO   test-name: maestro_cfg_test
2022-09-19 15:06:53,383 TADA INFO   test-user: narate
2022-09-19 15:06:53,383 TADA INFO   commit-id: d0f0efc0919dafdb8387c7a7dc69027d5e8949d5
2022-09-19 15:07:03,394 __main__ INFO -- Get or create cluster --
---Wait for config to write to file---
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/networks/narate-maestro_cfg_test-d0f0efc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 664, in _get
    net = dc.networks.get(name)
  File "/usr/lib/python3/dist-packages/docker/models/networks.py", line 180, in get
    self.client.api.inspect_network(network_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/network.py", line 213, in inspect_network
    return self._result(res, json=True)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("network narate-maestro_cfg_test-d0f0efc not found")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/narate/projects/ldms-test/LDMS_Test.py", line 1615, in get
    cluster = _cls._get(name)
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 667, in _get
    raise LookupError()
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5e33f7e160>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='whiteknight', port=2375): Max retries exceeded with url: /v1.35/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e33f7e160>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maestro_cfg_test", line 289, in <module>
    cluster = LDMSDCluster.get(spec['name'], create = True, spec = spec)
  File "/home/narate/projects/ldms-test/LDMS_Test.py", line 1622, in get
    return _cls.create(spec)
  File "/home/narate/projects/ldms-test/LDMS_Test.py", line 1593, in create
    cluster = _cls._create(spec)
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 416, in _create
    return cls.__create(**kwargs)
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 498, in __create
    tbl = [ [ cl.info()["ContainersRunning"], 0, cl ] for cl in clients ]
  File "/home/narate/projects/ldms-test/runtime/docker.py", line 498, in <listcomp>
    tbl = [ [ cl.info()["ContainersRunning"], 0, cl ] for cl in clients ]
  File "/usr/lib/python3/dist-packages/docker/client.py", line 179, in info
    return self.api.info(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 95, in info
    return self._result(self._get(self._url("/info")), True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='whiteknight', port=2375): Max retries exceeded with url: /v1.35/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5e33f7e160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-09-19 15:07:03,430 TADA INFO assertion 1, load maestro etcd cluster: skipped
2022-09-19 15:07:03,430 TADA INFO assertion 2, config ldmsd cluster with maestro: skipped
2022-09-19 15:07:03,431 TADA INFO assertion 3, verify sampler daemons: skipped
2022-09-19 15:07:03,431 TADA INFO assertion 4, verify L1 aggregator daemons: skipped
2022-09-19 15:07:03,431 TADA INFO assertion 5, verify L2 aggregator daemon: skipped
2022-09-19 15:07:03,431 TADA INFO assertion 6, verify data storage: skipped
2022-09-19 15:07:03,431 TADA INFO test maestro_cfg_test ended
2022-09-19 15:07:13 INFO: ----------------------------------------------
2022-09-19 15:07:13 INFO: ======== test-ldms ========
2022-09-19 15:07:13 INFO: CMD: /home/narate/projects/ldms-test/ldms-containers/test/test-ldms/test.sh
2022-09-19T15:07:13-05:00 INFO: starting test-samp-1
667dfdd234b6e4468ffdc967a8da9693e200781b2ee3d50972d63bf66abce631
2022-09-19T15:07:15-05:00 INFO: starting test-samp-2
c0145d968bc77c161d02bf03dbc6fcb751f759a88700f4d85ce8b4758b0a37eb
2022-09-19T15:07:16-05:00 INFO: starting test-samp-3
9a8948c6145177597bdfe1b2dad81da9441ee01d54a31b6db4b33391c70b9d13
2022-09-19T15:07:17-05:00 INFO: starting test-samp-4
68a1210be36ff292ed5cac5a6f44d5ec65218e2c249799069dd8b7e3b018bb55
2022-09-19T15:07:18-05:00 INFO: test-samp-1 is running
2022-09-19T15:07:18-05:00 INFO: test-samp-2 is running
2022-09-19T15:07:18-05:00 INFO: test-samp-3 is running
2022-09-19T15:07:18-05:00 INFO: test-samp-4 is running
2022-09-19T15:07:18-05:00 INFO: starting test-agg-11
2a54bcc950a6c2f225a637f091f5df1c2cdc678bf6a0de7c0c53fc3fb3e1c508
2022-09-19T15:07:19-05:00 INFO: starting test-agg-12
d668b60765782729c11fbf4dd343502b2abe230a935ffb024c85132390a3cd99
2022-09-19T15:07:20-05:00 INFO: test-agg-11 is running
2022-09-19T15:07:20-05:00 INFO: test-agg-12 is running
2022-09-19T15:07:20-05:00 INFO: starting test-agg-2
8a1fe56b2046e1a3fcbbc3cc3f4e2d7a0fc122fbc3f68baff06f91e03bc4078d
2022-09-19T15:07:21-05:00 INFO: test-agg-2 is running
2022-09-19T15:07:21-05:00 INFO: Collecting data (into SOS)
2022-09-19T15:07:31-05:00 INFO: Checking SOS data
Component IDs: {1, 2, 3, 4}
2022-09-19T15:07:32-05:00 INFO: check rc: 0
2022-09-19T15:07:32-05:00 INFO: Cleaning up ...
test-samp-1
test-samp-2
test-samp-3
test-samp-4
test-agg-11
test-agg-12
test-agg-2
2022-09-19T15:07:35-05:00 INFO: DONE
2022-09-19 15:07:45 INFO: ----------------------------------------------
2022-09-19 15:07:45 INFO: ======== test-maestro ========
2022-09-19 15:07:45 INFO: CMD: /home/narate/projects/ldms-test/ldms-containers/test/test-maestro/test.sh
2022-09-19T15:07:45-05:00 INFO: starting mtest-maestro
1743f01d47f27d142cf59384c486a44716aa71901263462a16195f4a9eed0cd7
2022-09-19T15:07:46-05:00 INFO: starting mtest-samp-1
9f545234d915e0d0c6cd895d5519d791d0690e426ae1c14d6dbe026dc37e1cb3
2022-09-19T15:07:47-05:00 INFO: starting mtest-samp-2
2c6455cb7a3325697cba4bc0fe8a718a965bf47d91606a61791d7903753b7b53
2022-09-19T15:07:47-05:00 INFO: starting mtest-samp-3
04cccec5c2c8a6b500de970c46958acfb7325183f8ae0a48e9f4cf523b94b845
2022-09-19T15:07:48-05:00 INFO: starting mtest-samp-4
b481cfefc92447ba95e5dba6243de8816962dcd276405c928348de7363e0d62d
2022-09-19T15:07:49-05:00 INFO: mtest-samp-1 is running
2022-09-19T15:07:49-05:00 INFO: mtest-samp-2 is running
2022-09-19T15:07:49-05:00 INFO: mtest-samp-3 is running
2022-09-19T15:07:49-05:00 INFO: mtest-samp-4 is running
2022-09-19T15:07:49-05:00 INFO: starting mtest-agg-11
d8d1fc53a2762ab7b8a132bf8241be3af89aff2b3faee7fa99951823f973148b
2022-09-19T15:07:50-05:00 INFO: starting mtest-agg-12
d845d761e1c69916ac60f6da9913c2d2c3db541ad78970bf862020a10d272c8a
2022-09-19T15:07:50-05:00 INFO: mtest-agg-11 is running
2022-09-19T15:07:50-05:00 INFO: mtest-agg-12 is running
2022-09-19T15:07:50-05:00 INFO: starting mtest-agg-2
27b8be3e25e454439fa536641e1ba239eb7c91729b56514df1df8a52b71d8a25
2022-09-19T15:07:51-05:00 INFO: mtest-agg-2 is running
2022-09-19T15:07:51-05:00 INFO: Collecting data (into SOS)
mtest-agg-11
mtest-agg-12
2022-09-19T15:08:02-05:00 INFO: Checking SOS data
Component IDs: {1, 2, 3, 4}
2022-09-19T15:08:03-05:00 INFO: sos check rc: 0
2022-09-19T15:08:04-05:00 INFO: starting mtest-ui
071e905004a58eb071a95ff776483385e99bffc49801f784be57ddd504318c95
2022-09-19T15:08:10-05:00 INFO: Checking query from mtest-ui: http://mtest-ui/grafana/query
query results: b'[{"target": "Active", "datapoints": [[2452000, 1663618075001.311], [2452000, 1663618075001.323], [2449160, 1663618076001.378], [2449160, 1663618076001.471], [2449160, 1663618076001.479], [2449160, 1663618076001.479], [2449556, 1663618077001.502], [2449556, 1663618077001.5842], [2449556, 1663618077001.617], [2449556, 1663618077001.618], [2449628, 1663618078001.655], [2449628, 1663618078001.698], [2449628, 1663618078001.769], [2449628, 1663618078001.769], [2449628, 1663618079001.772], [2449628, 1663618079001.823], [2449628, 1663618079001.935], [2449628, 1663618079001.935], [2447784, 1663618080001.251], [2447784, 1663618080001.943], [2447784, 1663618080001.987], [2447784, 1663618080001.987], [2447752, 1663618081001.3682], [2447752, 1663618081001.933], [2447752, 1663618081001.961], [2447752, 1663618081001.961]]}, {"target": "component_id", "datapoints": [[3, 1663618075001.311], [1, 1663618075001.323], [3, 1663618076001.378], [1, 1663618076001.471], [2, 1663618076001.479], [4, 1663618076001.479], [3, 1663618077001.502], [1, 1663618077001.5842], [4, 1663618077001.617], [2, 1663618077001.618], [3, 1663618078001.655], [1, 1663618078001.698], [2, 1663618078001.769], [4, 1663618078001.769], [3, 1663618079001.772], [1, 1663618079001.823], [2, 1663618079001.935], [4, 1663618079001.935], [3, 1663618080001.251], [1, 1663618080001.943], [2, 1663618080001.987], [4, 1663618080001.987], [3, 1663618081001.3682], [1, 1663618081001.933], [2, 1663618081001.961], [4, 1663618081001.961]]}, {"target": "job_id", "datapoints": [[0, 1663618075001.311], [0, 1663618075001.323], [0, 1663618076001.378], [0, 1663618076001.471], [0, 1663618076001.479], [0, 1663618076001.479], [0, 1663618077001.502], [0, 1663618077001.5842], [0, 1663618077001.617], [0, 1663618077001.618], [0, 1663618078001.655], [0, 1663618078001.698], [0, 1663618078001.769], [0, 1663618078001.769], [0, 1663618079001.772], [0, 1663618079001.823], [0, 1663618079001.935], [0, 1663618079001.935], [0, 1663618080001.251], [0, 1663618080001.943], [0, 1663618080001.987], [0, 1663618080001.987], [0, 1663618081001.3682], [0, 1663618081001.933], [0, 1663618081001.961], [0, 1663618081001.961]]}]'
comp_ids:{1, 2, 3, 4}
2022-09-19T15:08:11-05:00 INFO: query check RC: 0
3898fc3bc853160c0bf293c940712d2f0e2d4c161218a7fc8c4422a1310fe36d
2022-09-19T15:08:22-05:00 INFO: Adding DSOS data source in Grafana
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   479  100   366  100   113   6905   2132 --:--:-- --:--:-- --:--:--  9037
{"datasource":{"id":1,"uid":"fvPW2hn4z","orgId":1,"name":"SOS-2","type":"dsosds","typeLogoUrl":"","access":"proxy","url":"http://mtest-ui/grafana","user":"","database":"","basicAuth":false,"basicAuthUser":"","withCredentials":false,"isDefault":true,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"SOS-2"}
2022-09-19T15:08:23-05:00 INFO: Checking grafana data
2022-09-19T15:08:23-05:00 INFO: Grafana data check, rc: 0
2022-09-19T15:08:23-05:00 INFO: Cleaning up ...
mtest-samp-1
mtest-samp-2
mtest-samp-3
mtest-samp-4
mtest-agg-11
mtest-agg-12
mtest-agg-2
mtest-maestro
mtest-ui
mtest-grafana
2022-09-19T15:08:26-05:00 INFO: DONE
2022-09-19 15:08:36 INFO: ----------------------------------------------
2022-09-19 15:08:36 INFO: ======== test-maestro-hostmunge ========
2022-09-19 15:08:36 INFO: CMD: /home/narate/projects/ldms-test/ldms-containers/test/test-maestro-hostmunge/test.sh
2022-09-19T15:08:36-05:00 INFO: Checking munge on localhost
2022-09-19T15:08:36-05:00 INFO: munge encode/decode successfully
2022-09-19T15:08:36-05:00 INFO: starting mtest-maestro
7428f427f4443223a7645dc62c919ad76ad77b836aca9cc1a72b1deba2beb5e7
2022-09-19T15:08:38-05:00 INFO: starting mtest-samp-1
76618dc1b41afd08e9a72b8a9bea6f01434d4687b9fa7e7d436b16cbe425f94a
2022-09-19T15:08:38-05:00 INFO: starting mtest-samp-2
ac0145a0b0d44c8a6d39c8c4f638165e30a96af6710712c0e68e078a1c8444af
2022-09-19T15:08:39-05:00 INFO: starting mtest-samp-3
092b407abef82cea2216c2c5ed953675d71116ca41154efecd20feaddff43417
2022-09-19T15:08:40-05:00 INFO: starting mtest-samp-4
9e62f975c149cbbcdecb6776f52d76ebe55e7023ee4ec77c1f9152b01ee4f42e
2022-09-19T15:08:40-05:00 INFO: mtest-samp-1 is running
2022-09-19T15:08:40-05:00 INFO: mtest-samp-2 is running
2022-09-19T15:08:40-05:00 INFO: mtest-samp-3 is running
2022-09-19T15:08:41-05:00 INFO: mtest-samp-4 is running
2022-09-19T15:08:41-05:00 INFO: starting mtest-agg-11
785c8cd9c56bc1eb66ad5d06f67487fc2acf4400d21bfc7af0d5585a118f15b8
2022-09-19T15:08:41-05:00 INFO: starting mtest-agg-12
1612c611945bcbb4d570204870be8e9046e194e8140a429b0ef685f5136cedb3
2022-09-19T15:08:42-05:00 INFO: mtest-agg-11 is running
2022-09-19T15:08:42-05:00 INFO: mtest-agg-12 is running
2022-09-19T15:08:42-05:00 INFO: starting mtest-agg-2
1784b44d122d2b97480e228c15b7a0098bdd6b9643f04ede79e08238d6d57cbd
2022-09-19T15:08:43-05:00 INFO: mtest-agg-2 is running
2022-09-19T15:08:43-05:00 INFO: Collecting data (into SOS)
mtest-agg-11
mtest-agg-12
2022-09-19T15:08:53-05:00 INFO: Checking SOS data
Component IDs: {1, 2, 3, 4}
2022-09-19T15:08:54-05:00 INFO: sos check rc: 0
2022-09-19T15:08:56-05:00 INFO: starting mtest-ui
9a718be45501a2d12dff85cbcb502af174a8b699836e452aae5ebe741be510a8
2022-09-19T15:08:56-05:00 INFO: Checking query from mtest-ui: http://mtest-ui/grafana/query
query results: b'[{"target": "Active", "datapoints": [[2434684, 1663618128001.2422], [2434684, 1663618128001.865], [2434684, 1663618128001.929], [2434684, 1663618128002.019], [2437052, 1663618129001.169], [2437052, 1663618129001.346], [2437052, 1663618129001.92], [2437052, 1663618129001.923], [2437052, 1663618130001.3162], [2437052, 1663618130001.4531], [2437052, 1663618130001.918], [2437052, 1663618130001.944], [2437052, 1663618131001.46], [2437052, 1663618131001.563], [2437052, 1663618131001.946], [2437052, 1663618131001.955], [2437056, 1663618132001.604], [2437056, 1663618132001.675], [2437056, 1663618132001.919], [2437056, 1663618132001.92]]}, {"target": "component_id", "datapoints": [[4, 1663618128001.2422], [3, 1663618128001.865], [1, 1663618128001.929], [2, 1663618128002.019], [2, 1663618129001.169], [4, 1663618129001.346], [1, 1663618129001.92], [3, 1663618129001.923], [2, 1663618130001.3162], [4, 1663618130001.4531], [1, 1663618130001.918], [3, 1663618130001.944], [2, 1663618131001.46], [4, 1663618131001.563], [1, 1663618131001.946], [3, 1663618131001.955], [2, 1663618132001.604], [4, 1663618132001.675], [1, 1663618132001.919], [3, 1663618132001.92]]}, {"target": "job_id", "datapoints": [[0, 1663618128001.2422], [0, 1663618128001.865], [0, 1663618128001.929], [0, 1663618128002.019], [0, 1663618129001.169], [0, 1663618129001.346], [0, 1663618129001.92], [0, 1663618129001.923], [0, 1663618130001.3162], [0, 1663618130001.4531], [0, 1663618130001.918], [0, 1663618130001.944], [0, 1663618131001.46], [0, 1663618131001.563], [0, 1663618131001.946], [0, 1663618131001.955], [0, 1663618132001.604], [0, 1663618132001.675], [0, 1663618132001.919], [0, 1663618132001.92]]}]'
comp_ids:{1, 2, 3, 4}
2022-09-19T15:08:58-05:00 INFO: query check RC: 0
896d629efc005e5df9c30b238914304395ba116ae799ef4bbb80f9bb6310fa8b
2022-09-19T15:09:03-05:00 INFO: Adding DSOS data source in Grafana
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   479  100   366  100   113   7176   2215 --:--:-- --:--:-- --:--:--  9392
{"datasource":{"id":1,"uid":"XxqMh2n4k","orgId":1,"name":"SOS-2","type":"dsosds","typeLogoUrl":"","access":"proxy","url":"http://mtest-ui/grafana","user":"","database":"","basicAuth":false,"basicAuthUser":"","withCredentials":false,"isDefault":true,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"SOS-2"}
2022-09-19T15:09:04-05:00 INFO: Checking grafana data
2022-09-19T15:09:04-05:00 INFO: Grafana data check, rc: 0
2022-09-19T15:09:04-05:00 INFO: Cleaning up ...
mtest-samp-1
mtest-samp-2
mtest-samp-3
mtest-samp-4
mtest-agg-11
mtest-agg-12
mtest-agg-2
mtest-maestro
mtest-ui
mtest-grafana
2022-09-19T15:09:07-05:00 INFO: DONE
2022-09-19 15:09:17 INFO: ----------------------------------------------
2022-09-19 15:09:17 INFO: ======== test-maestro-munge ========
2022-09-19 15:09:17 INFO: CMD: /home/narate/projects/ldms-test/ldms-containers/test/test-maestro-munge/test.sh
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 0.000274655 s, 14.9 MB/s
2022-09-19T15:09:18-05:00 INFO: starting mtest-maestro
fa8e168c16316fcfb5ed4453f66781d40d04e9f83f97e107cf33520efedc06d9
2022-09-19T15:09:19-05:00 INFO: starting mtest-samp-1
29bc7064c113ca66e2a97b7a11b4c76bce78c6f5698b9df0a9dbc223f626f2da
2022-09-19T15:09:20-05:00 INFO: starting mtest-samp-2
53ed9cdd47e438acdd0891446b6ae3dfa2d57c08e580e047c265b4cf85df634d
2022-09-19T15:09:21-05:00 INFO: starting mtest-samp-3
a11b18e2af09bf01579f2721aec48b84cece5ab976856ca3d8b6d8cfc24ebb81
2022-09-19T15:09:22-05:00 INFO: starting mtest-samp-4
bce0201fe1c4f0fdcc885450e8d67ddd8778661e2c0e374483022c72b2ac213f
2022-09-19T15:09:22-05:00 INFO: mtest-samp-1 is running
2022-09-19T15:09:22-05:00 INFO: mtest-samp-2 is running
2022-09-19T15:09:22-05:00 INFO: mtest-samp-3 is running
2022-09-19T15:09:22-05:00 INFO: mtest-samp-4 is running
2022-09-19T15:09:22-05:00 INFO: starting mtest-agg-11
ba64ca506406216a39579d5da4b38718b2f4b51ff6937af954a0ee5118a138c7
2022-09-19T15:09:23-05:00 INFO: starting mtest-agg-12
85cd3fc4c7b3ac3861dc97a90960d2dc4b430b34daa70bee4bdd0f0af090a373
2022-09-19T15:09:24-05:00 INFO: mtest-agg-11 is running
2022-09-19T15:09:24-05:00 INFO: mtest-agg-12 is running
2022-09-19T15:09:24-05:00 INFO: starting mtest-agg-2
c9e696e8d31d07dde2deba1088c5c82b4b67efe689bf51b52bf9d2944340c3ee
2022-09-19T15:09:25-05:00 INFO: mtest-agg-2 is running
2022-09-19T15:09:25-05:00 INFO: Collecting data (into SOS)
mtest-agg-11
mtest-agg-12
2022-09-19T15:09:35-05:00 INFO: Checking SOS data
Component IDs: {1, 2, 3, 4}
2022-09-19T15:09:36-05:00 INFO: sos check rc: 0
2022-09-19T15:09:38-05:00 INFO: starting mtest-ui
5fb6ab241c9a7f90121ddff589846e030e1068bb453472ad5cc056bcbc042e66
2022-09-19T15:09:38-05:00 INFO: Checking query from mtest-ui: http://mtest-ui/grafana/query
query results: b'[{"target": "Active", "datapoints": [[2452468, 1663618169001.07], [2452468, 1663618169001.861], [2453300, 1663618170001.2249], [2453300, 1663618170001.2249], [2453300, 1663618170001.874], [2453300, 1663618170001.9321], [2453692, 1663618171001.292], [2453692, 1663618171001.3398], [2453692, 1663618171001.978], [2453692, 1663618171002.046], [2453692, 1663618172001.192], [2453692, 1663618172001.392], [2453692, 1663618172001.449], [2453692, 1663618172001.93], [2453696, 1663618173001.3389], [2453696, 1663618173001.492], [2453696, 1663618173001.56], [2453696, 1663618173001.93], [2452772, 1663618174001.25], [2452772, 1663618174001.46], [2452772, 1663618174001.677], [2452772, 1663618174002.048]]}, {"target": "component_id", "datapoints": [[1, 1663618169001.07], [3, 1663618169001.861], [1, 1663618170001.2249], [4, 1663618170001.2249], [2, 1663618170001.874], [3, 1663618170001.9321], [4, 1663618171001.292], [1, 1663618171001.3398], [2, 1663618171001.978], [3, 1663618171002.046], [3, 1663618172001.192], [4, 1663618172001.392], [1, 1663618172001.449], [2, 1663618172001.93], [3, 1663618173001.3389], [4, 1663618173001.492], [1, 1663618173001.56], [2, 1663618173001.93], [4, 1663618174001.25], [3, 1663618174001.46], [1, 1663618174001.677], [2, 1663618174002.048]]}, {"target": "job_id", "datapoints": [[0, 1663618169001.07], [0, 1663618169001.861], [0, 1663618170001.2249], [0, 1663618170001.2249], [0, 1663618170001.874], [0, 1663618170001.9321], [0, 1663618171001.292], [0, 1663618171001.3398], [0, 1663618171001.978], [0, 1663618171002.046], [0, 1663618172001.192], [0, 1663618172001.392], [0, 1663618172001.449], [0, 1663618172001.93], [0, 1663618173001.3389], [0, 1663618173001.492], [0, 1663618173001.56], [0, 1663618173001.93], [0, 1663618174001.25], [0, 1663618174001.46], [0, 1663618174001.677], [0, 1663618174002.048]]}]'
comp_ids:{1, 2, 3, 4}
2022-09-19T15:09:40-05:00 INFO: query check RC: 0
d3c6ba40d321c1ff3cc54f6a03626b8636b6b44cd52cbe020f5700d1d25a61fe
2022-09-19T15:09:45-05:00 INFO: Adding DSOS data source in Grafana
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   479  100   366  100   113   6777   2092 --:--:-- --:--:-- --:--:--  8870
{"datasource":{"id":1,"uid":"jPS4227Vk","orgId":1,"name":"SOS-2","type":"dsosds","typeLogoUrl":"","access":"proxy","url":"http://mtest-ui/grafana","user":"","database":"","basicAuth":false,"basicAuthUser":"","withCredentials":false,"isDefault":true,"jsonData":{},"secureJsonFields":{},"version":1,"readOnly":false},"id":1,"message":"Datasource added","name":"SOS-2"}
2022-09-19T15:09:46-05:00 INFO: Checking grafana data
2022-09-19T15:09:47-05:00 INFO: Grafana data check, rc: 0
2022-09-19T15:09:47-05:00 INFO: Cleaning up ...
mtest-samp-1
mtest-samp-2
mtest-samp-3
mtest-samp-4
mtest-agg-11
mtest-agg-12
mtest-agg-2
mtest-maestro
mtest-ui
mtest-grafana
2022-09-19T15:09:50-05:00 INFO: DONE
2022-09-19 15:10:00 INFO: ----------------------------------------------
2022-09-19 15:10:00 INFO: ==== Summary ====
agg_slurm_test: [01;31mFAILED[0m
cont-test-maestro-hostmunge: [01;32mPASSED[0m
maestro_cfg_test: [01;31mFAILED[0m
cont-test-maestro: [01;32mPASSED[0m
cont-test-ldms: [01;32mPASSED[0m
cont-test-maestro-munge: [01;32mPASSED[0m
------------------------------------------
Total tests passed: 4/6
------------------------------------------
